---
apiVersion: v1
kind: Service
metadata:
  name: unifi-console
  namespace: default
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 443
      name: admin
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unifi-console
  namespace: default
  labels:
    kubernetes.io/service-name: unifi-console
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.1
    conditions:
      ready: true
      serving: true
      terminating: false
ports:
  - port: 443
    protocol: TCP
    name: admin
