---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./bitwarden-sm-operator/ks.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./external-secrets/ks.yaml
  - ./intel/ks.yaml
  - ./kured/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./nvidia/dcgm-exporter/ks.yaml
  - ./nvidia/device-plugin/ks.yaml
  - ./snapshot-controller/ks.yaml
