---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: recovery
spec:
  dependsOn:
    - name: minio
      namespace: system
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      extraEnvVars:
        TZ: "UTC"
        MINIO_LOG_LEVEL: "DEBUG"
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: velero
          default: true
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: "http://minio.system.svc:9000"
            publicUrl: https://s3.${SECRET_DOMAIN}
      fsBackupTimeout: 4h
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    deployNodeAgent: true
    credentials:
      existingSecret: velero-credentials
    schedules:
      daily-backup:
        # At 6:00am in the morning every day
        schedule: "0 6 * * *"
        template:
          ttl: "168h"
      weekly-backup:
        # At the end of the week on a Sunday morning, at 6:00am
        schedule: "0 6 * * 0"
        template:
          ttl: "672h"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    backupsEnabled: true
    snapshotsEnabled: false
    upgradeCRDs: false
    cleanUpCRDs: false
    kubectl:
      image:
        repository: ghcr.io/onedr0p/kubernetes-kubectl
        tag: 1.27.3@sha256:fcc5372b0e1e3d51c0d3a95282fdfd80aeb389aa4077fd430276c511857313cf
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi