---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector
spec:
  hostnamePrefix: cluster
  subnetRouter:
    advertiseRoutes:
      - 192.168.0.0/16
  exitNode: true
  replicas: 2
