---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-auth
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        VPN_SERVICE_PROVIDER: "private internet access"
        OPENVPN_USER: |-
          {{ .username }}
        OPENVPN_PASSWORD: |-
          {{ .password }}
        SERVER_REGIONS: "CA Ontario"
        DOT: "off"
        FIREWALL: "off"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0281ebb5-ac6d-40a2-959c-ae9900eca084
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0281ebb5-ac6d-40a2-959c-ae9900eca084
        property: password
