apiVersion: v1
kind: Secret
metadata:
    name: sops-bw-secrets
    namespace: flux-system
type: Opaque
stringData:
    BW_ORG_ID: ENC[AES256_GCM,data:F3HOxIxeIXvdTTf+EwoR9ifV/o53XvM1slUhIR/QvSSd2RKx,iv:/jSXwx0hrOuVkAOEm0Av9BuZqdazi+iXEu7TwbGoJyk=,tag:2ZwAzNKUNvTUJmV4iXZNyA==,type:str]
    BW_PROJECT_ID: ENC[AES256_GCM,data:QYF6UCYP34ZEfusH0zS6/HrQroBx6PD/xcjf72FFIEOZcltG,iv:7VmaoL5tKjiCa8Jy5SSu8DerVJbNRmNW8L2c41chmfU=,tag:IkoG9KvjOaBlJFMp6olRVQ==,type:str]
    BW_PROJECT_TOKEN: ENC[AES256_GCM,data:YZK9EMJy82rufjYWZdb7D2DcMCQo6CnuvPppAxqdYuiOVQf32hV3ncaz+r0KmBZmkAD0BxVi8Sri7Asu4aiUh7WBGqYMmuVPVBg50c+UrUzeqaO2/8FeUHAIOaWEZw==,iv:t3D3PTBGQw6cAnHEinJYkm6f7TvGpIBQjJeYvN+dykI=,tag:FIDuPzbPAtgsVOT2H55q0A==,type:str]
sops:
    age:
        - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmRxVjBCYTllcVJud2lu
            UENpb1RVL2dWdlpxRUZDZk5sRGNXeHg4c1JVCmg4SlU0UU45OWxDRGFlVHlrQWN2
            bzhjVXA5a1kxUU91Qzc4YU5mcWZUVEEKLS0tIGNXV2NkWkhZUTZWTEtWcXBoUnlZ
            U25PU0dZcjNHdnJ5alZmY0lucWdvbTQKs6MeuY31b/bZwZFEZgO82kSjBBwvhCIt
            g9dh4OmBc09WuyPr3gay0PSzVEb2w870l1GXw+F6z+w8OujNwmfX8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T17:13:23Z"
    mac: ENC[AES256_GCM,data:d1SZH6mDZkx+dFMQB0FUtmsja4c2R0k46vRb6D/W7EZ7dBfniaO4VRBXDSthTV2YiaZ3kH+NnOOi1HKuSNHVaeTL+I6dr259nvAoRaYKzAcFT/mUOdltUWXHAIjRNMZuWsC9aCTwft3mT+RUEf5owJt5So4Z3v5MQ49GqX9Q2kM=,iv:VGfBWRtKsx/7ZLumaUxBedur6Nm73bqkS/nOoyfgYvo=,tag:o+qUlFEoRMQylVCC/FxKRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
