apiVersion: v1
kind: Secret
metadata:
    name: sops-op
    namespace: flux-system
type: Opaque
stringData:
    OP_CONNECT_TOKEN: ENC[AES256_GCM,data:nV4eVltmwW+MZtcWsDNVYL/Tv0quTBPTVmbXNb+8/60FwzZvryEFT2ppxurUfEyemd3xdGOwhvrAmaxa2XMLGPKwoX+usHWUJVZqlNizNPHCeJApi0eHoXRFF2x7/wwE/TTP3L3v3ixrpIR9iinp1AQ4qmym9I9W1Yn6KtvzPgr1vnf5CiFUU41L8Q8bH39ndJDg89pI4moHW5vM1G83ihq70nXKL+KGwER5QfXtO0xGprDbb2os32306okapQDakQtMg/l8G8E3wbUqwWCfdrf2d3YtpAVThxkgIuYcgMTMclujHq8PlH+weVbl4genZ+11EQoOFEWOBDusUa3mtIWIQ0DF1g3oJjKKcEAPA8FmowdLlos5MhVtZ3MV6Bdl3nrO4l+dZ5Nme6aKOME5OxZw05ODWRgicRJJFVivq18oGxQhpQ+zTpLNvL8K9/PrgLvLQ/jP7k6fXdB103/SCLg+96GKmHYPfwQu7ta5T81F5TbO36g6cttBdfcWl0u1lNX8uh4fkJz1JsZvFzUb03AVutwLW5I9bd5G2InCbOGZ9CU5ZMsiDy3/RGVXOh6kqf+TAoKisb/n5/tkh6Dj2WQgoB+G4o5UVLV7x5ONXR8sGSeGRkeeEv7Dd0UIUlxNI4T7Rck38ZXk8CXCj9YReU7kU56lRVH9RiZtFGSOCw7SngQOJycbsRgFP0514tEEU28klwYlqw6JTfEUapGjck4ExoR5WPTYLBEJg8M4Qyd7mAXAayF5jyuVhYCNddvbL6IYU4IfH35JlMQsUAfLkBSml+xOV+6Uz70J1lwI9uAOQlDyi6Uy7Kp8kngKT/JmRhvqYYTG5KEBLXBA105ocoT+,iv:oYofzwByu2Vlbim/aDlSlpcNjuzmB4ezH3d6t6Ypbp0=,tag:mmIZRoAyLA4x1CIZEzm08A==,type:str]
sops:
    age:
        - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNHZIMFBkbEJRSlkwUHNI
            NHM4a1pBZXpLYWFRb1NsYVdGaytVL01sT2hvCmNGR3dFZklHWjZVV3RzdkpkT0Z5
            WWF4cEJBdnJRaGhKZ0FVR3lUSTNXMUUKLS0tIGVwajF2RnltaTRheldQYkFTeGc4
            dWdUbkhNT3o3NDZWS3RNZEY4Zys3OTAKXqWvoG7I36UwcMozSyclv87lmL5YMkA3
            dD91FGBL/eJY1ON4+qJjy86urvmFrkEmp5tVb1OUba4Dcf29eI++qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T13:45:12Z"
    mac: ENC[AES256_GCM,data:SK5G7r7s/eVqGunJ+NavuNYpyuTYBWkdylBulYroqYB4ijh3CvwBwDOWMxcWhDbj2i67uRhjubOHcBV5bBBCVxPpZ26/OTmOzFgRLWd9MbQLS1cHra0N80Valavy8f+Re062dYPw4QYcHQLeZjQGyxkrNKIT8rCQw82VdyiT3hg=,iv:EBkf2Z+/NEWBTMlefYMG9UTBasV/A38f3IkCFZX+A28=,tag:5CO8Mij2CuFvKlwWDHBnvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
