apiVersion: v1
kind: Secret
metadata:
    name: sops-op
    namespace: flux-system
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:RMnjTDyXklUpWhMNkOMcpsv0Z0J7fYryaYfT+rkYV+GRKpqEHbvMt4U8J3H6ezOtNDgDJPeaXc75WXQyZqyh8o1aUcjuM3sKaemnRRHgdDn29QAsXbWroClIDB9qkS8GbbPH55yWlfkILJazthFagrOWakO5AKLEvuZOMUqOWlOmm0tSZEauyXYi2s0bKnskR6XZ3sCnKJW47Cwp98juUW0KgmENHD3x3Kbspsa/nrHTlnRwOC895SV/GZ+ML3EhXn8D8CbWL+GuAH8F3ZYGfPLARyb17ikuRW4dyLo/ZOjUsBgYs0WeghoC53tPt713TJ9ayc3k8hOdWq77Afhn+K6qDJ6Kg/woy2kgERlqK8qt9+083gXaZkiuzE+2OxYnOEVe7ufEExsHKUiV4f01h3UF0kJc6ZcwgVO1T/x/o5PVGArZbLLp5ZxBCHy0FXcQ2qrkjC9yTpT5apQrn85NFiMRR94DaC8Eeky1FjqcVLshVDb3sgLZKRCxD5ko7XOCAOwZPjmqwJsErzWjeUfdkPwQ0nKnUPOW62YPcSYAV7dPDNTru2tbo4/dM8GVA72dPj/uMHHpcCgCyfA55jQXWXTla7MtSJvNqj/OKCLumxMYlVJqkQNvsugzAMcjRy+s4jjkwGvkW4VnSiSW5HQ1w5Tq0/J2wKyxrSdS8FpqVCluNZHbCPb6I3i/UOrWtMGxKrnyfIvIo2EX2FwF0zbCt3ArvVo7g8bRTFHL5t3PLQT78oKr9kaygbxsJA2/fbfqLqvKHpTKV+ea2AudKhTfWfaB41BMTI4qiFIH1rA9MqP0ucOdPtCSbJzvbQdgbNA24xD612JIEFPhFW4x0WF/+NMZoSNCPhyOyyfNh3Qh4Lq0VWSy8cyXwTFVOzYyfRElaDSD5WygueSEkjDfUukn8uXt5SJE8fWPg7012z/lhEzSQuKtZ2CbIkZA19YMbsHuGMSEQI4fZFlJJZG82dkoTk1jTSqJwgmW0n/27AJh41gSBbvK1XLk+CNDvDdcMWsVEyPT+K+8ox3hh0PwaQOjLCBzdRoghvxV2cRz3DLcHHo3PoFexT5QTvBVyWeb2ON2gbZCnersuR8zw+sRqVm0MjXTBM+EhURBC+PFPZcQ4xHaOg==,iv:NeZk5j3q6iZqclBzn1kdDHMTBpWc0vUy5BgOiHi9Fa0=,tag:Ps4NB/SfrpOIMuORMxWYBw==,type:str]
sops:
    age:
        - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL2l3TlJDR0ZlWGR1bWJi
            ak05dGc4dFN2WDVKUDU3OGVWUXBTMlBSM0NzCnVQMTI0ZmpMdmtMd0l3ckJwalV1
            OGE3R2NPWTZmZGpHMnI1b1FoWE9CTXcKLS0tIFM5QWIvMUdEVy8xSEQvK3h4NjRv
            UnZoZ1JwQS9oRS9iL1RrbzU5aW9kZDAKdbALQjF9sSEOQVmXNKXtYPYzGnag+Hd5
            dGBb/TV/QtBSpVuzMgMTr6AqbFJaxwN9BHnuH05MbicQ6w65TT5uBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T19:50:56Z"
    mac: ENC[AES256_GCM,data:v1qDK6pL8HYP7v/MMThTMpUxt59RIGt8V9/oVpe9oFJwgChxIRT7Cc5j12zCaJkHVLoE2lQ5mR0jUFAOiCMmU/34r3GMFwLug+OdILumn+l4i2Rl7CR5PBxW0AkEa0kxMLUpBISZK3FY05kdIaUB562uKBXgYoq4xGnwXEvV8dc=,iv:xNWObjfPGT9yX2LJ1/WzcHZJohIvUO473jlmAMyM+Eg=,tag:5eSYz4OXe8cY3zV4ixDpLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
