---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: system
spec:
  dependsOn:
    - name: csi-driver-nfs
      namespace: system
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-01-18T22-51-28Z
            args: ["server", "/data", "--console-address", ":9001"]
            envFrom:
              - secretRef:
                  name: minio-secrets
            env:
              TZ: UTC
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_AUTH_TYPE: "public"
            auth:
              existingSecret: minio-secrets
        pod:
          annotations:
            secret.reloader.stakater.com/reload: minio-secrets
    service:
      main:
        enabled: true
        ports:
          http:
            port: &http-port 9001
          api:
            enabled: true
            port: &api-port 9000
    route:
      main:
        enabled: true
        parentRefs:
          - name: cilium-internal
            namespace: infrastructure
        hostnames:
          - "minio.garb.dev"
        rules:
          - backendRefs:
              - port: *http-port
                name: *app
      s3:
        enabled: true
        parentRefs:
          - name: cilium-internal
            namespace: infrastructure
        hostnames:
          - "s3.garb.dev"
        rules:
          - backendRefs:
              - port: *api-port
                name: *app
    persistence:
      config:
        enabled: true
        existingClaim: minio-csi
        globalMounts:
          - path: /data
