apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-controller.yaml
  - angelnu.yaml
  - bitnami.yaml
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - csi-driver-nfs.yaml
  - dashboard.yaml
  - descheduler.yaml
  - emberstack.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - grafana.yaml
  - hajimari.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - kube-state-metrics.yaml
  - kubereboot.yaml
  - kubernetes-sigs-nfd.yaml
  - longhorn.yaml
  - metallb.yaml
  - minio.yaml
  - nfs-provisioner.yaml
  - nvidia-dcgm.yaml
  - nvidia-device-plugin.yaml
  - nvidia-operator.yaml
  - ori-edge.yaml
  - prometheus-community.yaml
  - searxng.yaml
  - stakater.yaml
  - tf-controller.yaml
  - vmware-tanzu.yaml
  - weaveworks.yaml
