---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitwarden.yaml
  - ./bjw-s.yaml
  - ./concourse.yaml
  - ./coredns.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./dashboard.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./emberstack.yaml
  - ./envoy-proxy.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./kube-state-metrics.yaml
  - ./kubereboot.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./longhorn.yaml
  - ./minio.yaml
  - ./nfs-provisioner.yaml
  - ./nvidia-dcgm.yaml
  - ./nvidia-device-plugin.yaml
  - ./nvidia-operator.yaml
  - ./ori-edge.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./tofu-controller.yaml
