---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    env:
      TZ: "UTC"
    hajimari:
      title: The Machine
      lightTheme: tron
      darkTheme: tron
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      showAppInfo: true
      defaultEnable: true
      defaultAppIcon: mdi:application
      defaultSearchProvider: Searx
      namespaceSelector:
        matchNames:
          - default
          - frigate
          - home
          - vpn
          - system
          - networking
          - mail
          - external
      customApps:
        - name: OPNSense
          url: "https://opnsense.${SECRET_DOMAIN}"
          icon: simple-icons:opnsense
        - name: Minio
          url: "https://minio.${SECRET_DOMAIN}"
          icon: box
        - name: hubble
          url: "https://hubble.${SECRET_DOMAIN}"
          icon: simple-icons:cilium
      globalBookmarks:
        - group: Dev
          bookmarks:
            - name: GitHub
              url: "https://github.com"
              icon: mdi:github
        - group: Cloud
          bookmarks:
            - name: ProtonMail
              url: "https://proton.me"
              icon: cib:protonmail
            - name: Bitwarden
              url: "https://vault.bitwarden.com"
              icon: simple-icons:bitwarden
            - name: Messenger
              url: "https://facebook.com/messages"
              icon: cib:messenger
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
              icon: cib:cloudflare
        - group: Kubernetes
          bookmarks:
            - name: larivierec/home-cluster
              url: "https://github.com/larivierec/home-cluster"
              icon: mdi:github
            - name: larivierec/containers
              url: "https://github.com/larivierec/containers"
              icon: mdi:github
            - name: larivierec/cloudflare-ddns
              url: "https://github.com/larivierec/cloudflare-ddns"
              icon: mdi:github
            - name: k8s-at-home-search
              url: "https://whazor.github.io/k8s-at-home-search/"
        - group: Shopping
          bookmarks:
            - name: "Amazon Canada"
              url: "https://amazon.ca/"
      searchProviders:
        - name: Searx
          token: w
          icon: ci:search
          searchUrl: https:/search.${SECRET_DOMAIN}/search?q={query}
          url: https://search.${SECRET_DOMAIN}
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: y
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M