services:
  bitwarden-sdk-server:
    image: ghcr.io/external-secrets/bitwarden-sdk-server:v0.5.1
    container_name: bitwarden-sdk-server
    ports:
      - "9998:9998"
    volumes:
      - .certificate/server.crt:/certs/cert.pem:ro
      - .certificate/server.key:/certs/key.pem:ro
      - .certificate/ca.crt:/certs/ca.pem:ro
    restart: unless-stopped
