---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-creds
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: |- 
          {{ .cloudflare_token }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: cloudflare_token
