---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-creds
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_CLOUDFLARE_API_TOKEN: |- 
          {{ .cloudflare_token }}
  refreshInterval: 15s
  data:
    - secretKey: cloudflare_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c6da36ed-305d-4806-9f5e-afed01755531
        property: cloudflare_token
