apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-driver-nfs-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  timeout: 3m