---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-metrics-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://kubernetes.github.io/kube-state-metrics
  timeout: 3m
