apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - coredns-charts.yaml
  - grafana-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - minio-charts.yaml
  - prometheus-community-charts.yaml
  - vmware-tanzu-charts.yaml
  - bananaspliff-charts.yaml
  - kube-state-metrics-charts.yaml
  - metallb-charts.yaml
