---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nvidia-plugin
  namespace: flux-system
spec:
  interval: 15m
  url: https://nvidia.github.io/k8s-device-plugin
  timeout: 3m
