---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-gpu-operator
  namespace: flux-system
spec:
  path: ./kubernetes/utility/apps/kube-system/intel/gpu-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugin-gpu
  namespace: flux-system
spec:
  path: ./kubernetes/utility/apps/kube-system/intel/device-plugin-gpu
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
