# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_CLOUDFLARE_TOKEN: |-
          {{ .token }}
        SECRET_CLOUDFLARE_TUNNEL: |-
          {{ .tunnel }}
        SECRET_GRAFANA_PASSWORD: |-
          {{ .grafana_password }}
        SECRET_DOMAIN: |-
          {{ .domain }}
        SECRET_EMAIL: |-
          {{ .email }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: cloudflare
  data:
    - secretKey: grafana_password
      remoteRef:
        key: grafana
        property: admin_password
