---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./alertmanager-discord/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./network-ups-client/ks.yaml
  - ./network-ups-tools/ks.yaml
  - ./network-ups-tools-office/ks.yaml
  - ./opnsense/ks.yaml
  - ./thanos/ks.yaml
  - ./vector/ks.yaml
