---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-creds
  namespace: database
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: |-
          {{ .mongo_pw }}
        MONGO_USER: |-
          {{ .mongo_user }}
        MONGO_PASSWORD: |-
          {{ .mongo_pw }}
        # MONGO_INITDB_DATABASE: "mongo"
  refreshInterval: 15m
  data:
    - secretKey: mongo_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: mongo_user
    - secretKey: mongo_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: mongo_pw
