---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./pvc.yaml
  - ./external-secret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: mongo-init
    files:
      - ./config/init-db.js
generatorOptions:
  disableNameSuffixHash: true
