---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.12.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller?ref=v0.12.0
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.11.0
