---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-creds
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        creds.json: |- 
          {{ .cloudflared_json }}
  refreshInterval: 15s
  data:
    - secretKey: cloudflared_json
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c6da36ed-305d-4806-9f5e-afed01755531
        property: cloudflared_json
