---
connectIPVersion: v4
upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one
      - tcp-tls:dns.quad9.net
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  timeout: 2s
conditional:
  mapping:
    cluster.local: 10.43.0.10
    garb.dev: 10.43.6.210
bootstrapDns:
  upstream: tcp-tls:one.one.one.one
  ips:
    - 1.1.1.1
filtering:
  queryTypes:
    - AAAA
    - HTTPS
# https://github.com/0xERR0R/blocky/issues/1273
ede:
  enable: false
redis:
  required: false
  address: redis-master
  sentinelAddresses:
    - redis-node-0.redis-headless.database.svc.cluster.local:26379
    - redis-node-1.redis-headless.database.svc.cluster.local:26379
    - redis-node-2.redis-headless.database.svc.cluster.local:26379
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/lists.php?type=nocross
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    trackers:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    noblock: []
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/larivierec/home-cluster/main/kubernetes/apps/networking/blocky/app/config/whitelist.txt
    trackers:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/larivierec/home-cluster/main/kubernetes/apps/networking/blocky/app/config/whitelist.txt
    noblock: []
  clientGroupsBlock:
    default:
      - ads
      - trackers
      - noblock
    192.168.10.249/32:
      - noblock
    192.168.10.8/32:
      - noblock
    192.168.1.132/32:
      - noblock
    MBPdeMalisabeth*:
      - noblock
    mefouquetbouchard-mbp*:
      - noblock
    marie-mba-work*:
      - noblock
clientLookup:
  upstream: 192.168.1.1
caching:
  prefetching: true
  prefetchExpires: 2h
  minTime: 5m
  cacheTimeNegative: -1m
prometheus:
  enable: true
  path: /metrics
ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000
certFile: /tls/tls.crt
keyFile: /tls/tls.key
log:
  level: info
  format: text
