---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name headlamp-admin
  namespace: flux-system
spec:
  deletionPolicy: Delete
  refreshInterval: 15m
  secretStoreRefs:
    - name: bitwarden-secrets-manager-sdk
      kind: ClusterSecretStore
  selector:
    secret:
      name: headlamp-admin
  template:
    engineVersion: v2
    data:
      password: |
        {
          "token": "{{ index . "password" }}"
        }
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: *name
          property: password
