# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-lidarr
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        LIDARR__API_KEY: |-
          {{ .api_key }}
        LIDARR__POSTGRES_HOST: &dbHost postgres-lb.database.svc
        LIDARR__POSTGRES_USER: &dbUser |-
          {{ .pg_user }}
        LIDARR__POSTGRES_PASSWORD: &dbPass |-
          {{ .pg_pass }}
        LIDARR__POSTGRES_MAIN_DB: lidarr-main
        LIDARR__POSTGRES_LOG_DB: lidarr-log
        INIT_POSTGRES_DBNAME: lidarr-main lidarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .root_password }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: postgres
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-lidarr
  namespace: default
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager-sdk
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/lidarr"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: minio_tf_volsync
    - extract:
        key: minio
    - extract:
        key: restic
