---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
  namespace: actions-runner-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        github_app_private_key: |-
          {{ .actions_runner_pk }}
        github_app_id: "{{ .actions_runner_app_id }}"
        github_app_installation_id: "{{ .actions_runner_app_installation_id }}"
  refreshInterval: 15m
  data:
    - secretKey: actions_runner_pk
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: be61938d-26d6-4900-a308-b06400ec40ff
    - secretKey: actions_runner_app_id
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: actions_runner_app_id
    - secretKey: actions_runner_app_installation_id
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: actions_runner_app_installation_id
