---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/charts
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
