mqtt:
  host: 192.168.42.2
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.8.3:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - rtmp
            - record
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: False
  camera_2:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.8.5:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - rtmp
            - record
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: False