---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-radarr
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RADARR__API_KEY: |-
          {{ .radarr_api_key }}
        RADARR__POSTGRES_HOST: &dbHost postgres-v16-rw.database.svc
        RADARR__POSTGRES_USER: &dbUser |-
          {{ .postgres_radarr_user }}
        RADARR__POSTGRES_PASSWORD: &dbPass |-
          {{ .postgres_radarr_pass }}
        RADARR__POSTGRES_MAIN_DB: radarr-main
        RADARR__POSTGRES_LOG_DB: radarr-log
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr-main radarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: radarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: radarr_api_key
    - secretKey: postgres_radarr_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_radarr_user
    - secretKey: postgres_radarr_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_radarr_pass
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
