---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pod-gateway
  - ingress-nginx
  - ingress-nginx-internal
  - blocky
  - cloudflared
  - ddns
  - external-dns
  - k8s-gateway
  - opnsense
  - proxmox
