---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      timeZone: "America/New_York"
      startTime: "3am"
      endTime: "6am"
      notifyUrl: "http://alertmanager-discord.monitoring.svc.cluster.local:9094"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    metrics:
      create: true
