---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        mqtt_password: |-
          {{ .mqtt_password }}
        rtsp_user: |-
          {{ .rtsp_user }}
        rtsp_password: |-
          {{ .rtsp_password }}
  refreshInterval: 15s
  data:
    - secretKey: mqtt_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c6da36ed-305d-4806-9f5e-afed01755531
        property: mqtt_password
    - secretKey: rtsp_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c6da36ed-305d-4806-9f5e-afed01755531
        property: rtsp_user
    - secretKey: rtsp_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c6da36ed-305d-4806-9f5e-afed01755531
        property: rtsp_password
