---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  dependsOn:
    - name: mosquitto
      namespace: home
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    runtimeClassName: nvidia
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.12.1-tensorrt
      imagePullPolicy: IfNotPresent
    controller:
      strategy: Recreate
    securityContext:
      privileged: true
    env:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
      NVIDIA_VISIBLE_DEVICES: all
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        annotations:
          # io.cilium/lb-ipam-ips: "192.168.42.10"
          hajimari.io/icon: icon-park-solid:surveillance-cameras 
        ingressClassName: nginx-internal
        hosts:
          - host: &host "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    configMaps:
      config:
        enabled: false
    persistence:
      data:
        enabled: true
        existingClaim: frigate-config
      config:
        enabled: true
        type: configMap
        name: &config frigate-config
        subPath: config.yml
        mountPath: /config/config.yml
        readOnly: true
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.1.5"
            path: "/volume2/frigate"
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        mountPath: /dev/shm
        medium: Memory
        sizeLimit: 4Gi
      tensor:
        enabled: true
        type: hostPath
        hostPath: /opt/gpu/trt-models
        mountPath: /trt-models
        hostPathType: Directory
        readOnly: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
        nvidia.com/gpu: 1
      limits:
        memory: 6Gi
        nvidia.com/gpu: 1

  valuesFrom:
    - kind: Secret
      name: frigate
      valuesKey: mqtt_password
      targetPath: env.FRIGATE_MQTT_PASSWORD
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_user
      targetPath: env.FRIGATE_RTSP_USERNAME
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password
      targetPath: env.FRIGATE_RTSP_PASSWORD
      optional: false
