---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./csi-driver-nfs/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./spegel/ks.yaml
  - ./stakater/ks.yaml
  - ./reflector/ks.yaml
  - ./minio/ks.yaml
  - ./unifi/ks.yaml
  - ./vaultwarden/ks.yaml
