---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-terraform-cloudflare
  namespace: infrastructure
spec:
  interval: 1m
  url: oci://ghcr.io/larivierec/terraform/cloudflare
  ref:
    tag: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: cloudflare
  namespace: infrastructure
spec:
  interval: 12h
  approvePlan: "auto"
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  path: ./
  sourceRef:
    kind: OCIRepository
    name: oci-terraform-cloudflare
    namespace: infrastructure
  tfstate:
    forceUnlock: "no"
  runnerPodTemplate:
    spec:
      volumeMounts:
        - name: tf-controller-sops-key
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
      volumes:
        - name: tf-controller-sops-key
          secret:
            secretName: sops-age
            items:
              - key: age.key
                path: keys.txt
