---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking
  - cert-manager
  - monitoring
  - flux-system
  - external
  - home
  - default
  - vpn
  - system
  - recovery
  - mail
  - system-upgrade
  - longhorn
  - database
  - infrastructure
  - actions-runner-system
