---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-system-notifications-discord
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/flux-system/notifications/discord"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-system-notifications-monitor
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/flux-system/notifications/discord"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true