---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blocky
  namespace: networking
spec:
  groups:
    - name: blocky
      rules:
        - alert: BlockyAbsent
          annotations:
            description: Blocky has disappeared from Prometheus service discovery.
            summary: Blocky is down.
          expr: |
            absent(up{job=~".*blocky.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: BlockyDisabled
          annotations:
            description: Blocky's ad blocking has been disabled for 15min. Please re-enable protection.
            summary: Blocky is disabled.
          expr: |
            blocky_blocking_enabled{job=~".*blocky.*"} == 0
          for: 15m
          labels:
            severity: critical
