---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-auth
  namespace: vpn
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        WIREGUARD_ADDRESSES: "10.14.0.2/16"
        WIREGUARD_PRIVATE_KEY: |-
          {{ .private_key }}
        WIREGUARD_PUBLIC_KEY: |-
          {{ .public_key }}
        SERVER_REGIONS: "Canada Toronto"
  refreshInterval: 15m
  data:
    - secretKey: private_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: wireguard_private
    - secretKey: public_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: wireguard_public
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-prowlarr
  namespace: vpn
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PROWLARR__API_KEY: |-
          {{ .prowlarr_api_key }}
        PROWLARR__POSTGRES_HOST: &dbHost postgres-v16-rw.database.svc
        PROWLARR__POSTGRES_USER: &dbUser |-
          {{ .postgres_prowlarr_user }}
        PROWLARR__POSTGRES_PASSWORD: &dbPass |-
          {{ .postgres_prowlarr_pass }}
        PROWLARR__POSTGRES_MAIN_DB: prowlarr-main
        PROWLARR__POSTGRES_LOG_DB: prowlarr-log
        # Postgres Init
        INIT_POSTGRES_DBNAME: prowlarr-main prowlarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: prowlarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: prowlarr_api_key
    - secretKey: postgres_prowlarr_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_prowlarr_user
    - secretKey: postgres_prowlarr_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_prowlarr_pass
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-qbittorrent
  namespace: vpn
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/qbittorrent"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: minio-s3-endpoint
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: restic_password
