---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-qbittorrent-0
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: qbittorrent-bootstrap
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: qbittorrent-bootstrap
  namespace: vpn
spec:
  trigger:
    manual: restore-once
  restic:
    repository: volsync-qbittorrent
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 8Gi
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    capacity: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: qbittorrent
  namespace: vpn
spec:
  sourcePVC: config-qbittorrent-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: volsync-qbittorrent
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 8Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 10
      weekly: 5
