---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garb-arc-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: garb-arc-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: garb-arc-runner
    namespace: arc-system
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: garb-arc-runner
spec:
  roles:
    - os:admin
