---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.21
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2
    resources:
      requests:
        cpu: 50m
        memory: 100Mi 
    env:
      TZ: UTC
    service:
      main:
        enabled: true
        ports:
          http:
            port: 4000
      dns-udp:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky-svc
          metallb.universe.tf/loadBalancerIPs: "192.168.42.4"
          # io.cilium/lb-ipam-ips: "192.168.42.4"
        monitor:
          enabled: false
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
      dns-tcp:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky-svc
          metallb.universe.tf/loadBalancerIPs: "192.168.42.4"
          # io.cilium/lb-ipam-ips: "192.168.42.4"
        monitor:
          enabled: false
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-dot:
            enabled: true
            port: 853
            protocol: TCP
            targetPort: 853
          dns-https:
            enabled: true
            port: 443
            protocol: TCP
            targetPort: 443
  
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config blocky-config
        subPath: config.yml
        mountPath: /app/config.yml
        readOnly: true
      tls:
        enabled: true
        type: secret
        name: wildcard-cert-tls
        readOnly: true

    configMaps:
      config:
        enabled: true
        data:
          config.yml: |-
            upstream:
              default:
                - tcp-tls:one.one.one.one
                - tcp-tls:dns.quad9.net
                - tcp-tls:protected.canadianshield.cira.ca
                - https://cloudflare-dns.com/dns-query
                - https://dns.quad9.net/dns-query
                - https://protected.canadianshield.cira.ca/dns-query


            upstreamTimeout: 2s

            conditional:
              mapping:
                ${SECRET_DOMAIN}: 10.43.131.47:53

            bootstrapDns:
              upstream: tcp-tls:one.one.one.one
              ips:
              - 1.1.1.1

            redis:
              address: redis.database.svc:6379
              database: 2
              required: true
              connectionAttempts: 10
              connectionCooldown: 3s

            blocking:
              blackLists:
                ads:
                  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                  - https://adaway.org/hosts.txt
                  - https://v.firebog.net/hosts/lists.php?type=nocross
                  - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
                  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
                  - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
                  - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
                  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
                  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
                  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
                noblock: []

              clientGroupsBlock:
                default:
                  - ads
                  - noblock
                192.168.1.129/32:
                  - noblock
                192.168.1.224/32:
                  - noblock
                192.168.1.249/32:
                  - noblock
                192.168.10.129/32:
                  - noblock
                192.168.10.224/32:
                  - noblock
                192.168.10.249/32:
                  - noblock
                MBPdeMalisabeth*:
                  - noblock
                Marie*:
                  - noblock

            clientLookup:
              upstream: tcp+udp:192.168.1.1

            caching:
              prefetching: true
              minTime: 5m
              maxTime: 5m
              cacheTimeNegative: -1m

            prometheus:
              enable: true
              path: /metrics

            ports:
              https: 443
              tls: 853
              http: 4000
            certFile: /tls/tls.crt
            keyFile: /tls/tls.key
            logLevel: info
            connectIPVersion: v4

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
      secret.reloader.stakater.com/reload: wildcard-cert-tls
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
