---
name: Schedule - Update Flux

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  flux-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Install Flux
        uses: fluxcd/flux2/action@main
      - name: Upgrade Flux
        id: upgrade
        run: |
          OLD_VERSION="$(flux -v)"
          VERSION="v${OLD_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --network-policy=false \
            --export > ./cluster/base/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          branch: "ci/flux-update-${{ steps.upgrade.outputs.flux_version }}"
          delete-branch: true
          title: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          signoff: true
          committer: "Christopher Larivière <lariviere.c@gmail.com>"
          author: "Christopher Larivière <lariviere.c@gmail.com>"
          assignees: "larivierec"
          commit-message: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}
          labels: flux/upgrade
