---
name: Lint Markdown files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ["arc-runner-set-home-cluster", "ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RIVER_BOT_ID }}
          private_key: ${{ secrets.RIVER_BOT_PK }}
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: "**.md"
      - name: Lint files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: "${{ steps.generate_token.outputs.token }}"
          markdownlint_flags: "-c '.github/lint/.markdownlint.yaml' ${{ steps.filter.outputs.markdown_files }}"
