---
name: Schedule - Add Helm Release Renovate annotations

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GitHub App token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Renovate
        uses: renovatebot/github-action@v31.44.0
        with:
          configurationFile: .github/renovate.json5
          token: "x-access-token:${{ steps.generate-token.outputs.token }}"
      - name: Create pull request for renovatebot helm-release annotations
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: renovate-annotations
          delete-branch: true
          title: "chore(deps): update renovate annotations"
          signoff: true
          committer: "Christopher Larivière <lariviere.c@gmail.com>"
          author: "Christopher Larivière <lariviere.c@gmail.com>"
          assignees: "larivierec"
          commit-message: "chore(deps): update renovate annotations"
          body: |
            Update Helm Releases in order for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations
