---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.28.4+k3s2"
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: DoesNotExist }
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "server"]
  upgrade:
    image: rancher/k3s-upgrade
